[tool.poetry]
name = "npc-generator"
version = "0.1.0"
description = ""
authors = ["suskikoodaa <suskeskitalo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
